# Introduction to Python

by Dominik Krzemiński & Piotr Migdał

for El Passion, 2017

Useful resources:

- [Ruby vs Python](http://learn.onemonth.com/ruby-vs-python)

- [Learn Python in Y Minutes](https://learnxinyminutes.com/docs/python3/)

- [Official Python tutorial](https://docs.python.org/3/tutorial/)

## Python interactive console

plus the power of IPython notebook

Python as a calculator:

In [ ]:
2 + 5

In [ ]:
8 * 8.583 * 0.927 * 2

In [ ]:
21 % 2

In [ ]:
21/3

In [ ]:
21//3

Default data types in Python:

In [ ]:
type(8 * 8.583 * 0.927 * 2)

In [ ]:
type(int(8 * 8.583 * 0.927 * 2))

In [ ]:
type(bin(int(8 * 8.583 * 0.927 * 2)))

## Python state of the art

### Functions

Below you can see an example of function with default argument:

In [ ]:
def should_i_work(day_of_week, phd_student=True):
    # here we check if list of strings contains our parameter
    if day_of_week in ["Monaday", "Tuesday", "Wednesday", "Thursday", "Friday"]:
        print("Yes!")
    # if not we check if the parameter is exactly Saturday
    elif day_of_week == "Saturday":
        if phd_student:
            print("Yes :/")
        else:
            print("No :)")
    # or Sunday
    elif day_of_week == "Sunday":
        print("No")
    # 
    else:
        print("It's not even a day. You are overworked!")

We can accept also unknown number of arguments:

In [ ]:
def fun(*args):
    for i in args:
        print(i)
        
fun(1,2,3,4)

### Loops

In [ ]:
for i in [1, 2, 3, 4, 5]:
    print(i)

In [ ]:
x = 0
while x < 5:
    x += 1

## Basic datatypes

### Lists

In [ ]:
lst = [1, 2, 3, "a"]

In [ ]:
lst.append(99)
lst

In [ ]:
lst.pop()

In [ ]:
lst[0]

In [ ]:
lst[-1]

In [ ]:
lst[::-1]

In [ ]:
len(lst)

Before running a line below, think about whether such an operation makes sense?

In [ ]:
sum(lst)

In [ ]:
lst.pop(lst.index("a"))

In [ ]:
sum(lst)

### Sets

In [ ]:
s = set([1, 1, 2, 2, 3, 3])

In [ ]:
print('Before:', len(s))
s.add(3)
print('Added 3:', len(s))
s.add(8)
print('Added 8:', len(s))

### Dictionaries

In [ ]:
d1 = dict([("a", 1), ("b", [1, 2, 3]), ("c", "abc")])
d2 = {"a" : 1, "b" : [1, 2, 3], "c" : "abc"}
d1 == d2

In [ ]:
"a" in d1

In [ ]:
for k, v in d1.items():
    print(k, v)

## Objects

In [10]:
class Duck(object):

    def __init__(self, name):
        self.name = name

    def quack(self):
        return "quack"

## Python tricks

### Iteratros

In [ ]:
range(1, 9)

In [ ]:
for i in range(1, 9):
    print(i, end=" ")

In [ ]:
list(range(1, 9))

### Generators (*)

In [ ]:
def gen_doubles():
    i = 0
    while True:
        i += 1
        yield 2*i


In [ ]:
for i in gen_doubles():
    print(i, end= " ")
    if i >= 20:
        break

### List comprehension

In [ ]:
[x for x in range(9, 15)]

In [ ]:
[x if x % 2 else "spam" for x in range(9, 15)]

Works also with tuples and dictionaries!

### Map/zip

Two must have functions while dealing with sequential data.

In [ ]:
for i in map(len, ["python", "ruby", "java"]):
    print(i)

In [ ]:
for number, text in zip(range(3), ["python", "ruby", "java"]):
    print(number, text)

### Exercises 1.1

(a) Count number of distinct elements in list `a`.

```
a = [1,2,3,3,3,3,4,5,1,2,3,5,4,3,2,1,2,3]
```

In [ ]:
a = [1,2,3,3,3,3,4,5,1,2,3,5,4,3,2,1,2,3]
len(set(a))

(b) Write a function that takes a list of numbers (for example, `a = [0, 5, 10, 15, 20]`) and makes a new list of only the first and last elements of the given list.

In [ ]:
def first_and_last(a):
    return [a[0], a[-1]]

(c) Implement a binary search function `binary_search(a, item)`.

In [ ]:
def binary_search(a, item):
    first = 0
    last = len(a)-1
    target = False
    while first <= last and not target:
        m = (first + last)//2
        if a[m] == item:
            target = True
        else:
            if item < a[m]:
                last = m - 1
            else:
                first = m + 1
    return target

(d) Write one line command to give a sum of all odd numbers from 1 to 100 inclusive.

In [ ]:
sum([i for i in range(1, 101) if i % 2 == 1])

(e) Invert a dictionary: `d = {'a': 1, 'b': 2, 'c': 3, 'd': 4}` (possible in one line)

In [ ]:
d = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
{d[k] : k for k in d}

(f) Squares each item in the items list using `map`.
```
items = [1, 3, 4, 6, 8]
```

In [ ]:
def f(x): return x**2
items = [1, 3, 4, 6, 8]
list(map(f, items))

(g) Count number of items in a dictionary value that is a list.
```
d =  {'a': [1, 2, 3], 'd': ['s1', 's2']}
```

In [ ]:
d =  {'a': [1, 2, 3], 'd': ['s1', 's2']}
sum(map(len, d.values()))

## String Manipulation

In [ ]:
"It is a string"

You can perform some arithmetic operation on strings (if it makes sense...)

In [ ]:
"Ruby is cool" + " " + "but Python cooler"

In [ ]:
5 * "la"

In [ ]:
"Our result number {n} is: {ratio:.3f}".format(n=15, ratio=3/7)

Strings are objects (as everything is Python) and have some useful methods:

In [ ]:
"snake".upper()

In [ ]:
"snake".replace("sn", "dr")

In [ ]:
"snake".find("ak")

Strings can be indexed just as lists:

In [ ]:
"It is a whole sentence!"[6:13]

In [ ]:
"It is a whole sentence!"[-3:]


In [ ]:
len("It is a whole sentence!")

In [ ]:
"It\nis\na\nmultiline\nthing\n!!!"

In [ ]:
print("It\nis\na\nmultiline\nthing\n!!!")

In [ ]:
" ".join(["a" , "b", "c"])

### Exercises 1.2

(a) Print every second letter from a string a in reversed order. (one-liner)

In [ ]:
a = "abcdefghij"
a[::2][::-1]

(b) Write a function writing to terminal histogram of given numbers. For example for numbers `3, 6, 4` it should look like:
```
***
******
****
```

In [ ]:
def txthist(x):
    for i in x:
        print('*'*i)

txthist([3, 6, 4])

(c) Write a function which accepts many strings and glue them together.

In [ ]:
def joiner(*args):
    return "".join(args)

var1 = "th"
var2 = "on"
joiner("py", var1, var2)

(d) Write a function which exchanges every letter in string input to `duck`. Letter should be defined as a parameted with default `"a"`.

In [ ]:
def duckenizer(inp, char="a"):
    "".join(["duck" if i=="" else i for i in inp])
    "duck".join(inp.split(char))
    return inp.replace(char,"duck")

duckenizer("annapurna")

## A quick glance at NumPy

NumPy is the fundamental package for scientific computing with Python. It contains a powerful N-dimensional array object, sophisticated (broadcasting) functions, tools for integrating C/C++ and Fortran code, useful linear algebra, Fourier transform, and random number capabilities.

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)
a

In [3]:
a.shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.ndim

2

In [8]:
(a + 1)*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [7]:
x = np.linspace( 0, 2*np.pi, 100 )
np.sin(x)

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,