# Machine Learning in Python

by [Piotr Migdał](http://p.migdal.pl/)

Inkubator Uniwersytetu Warszawskiego

## 1. Introduction to Python

Useful resources:

- [Ruby vs Python](http://learn.onemonth.com/ruby-vs-python)

- [Learn Python in Y Minutes](https://learnxinyminutes.com/docs/python3/)

- [Official Python tutorial](https://docs.python.org/3/tutorial/)

## Python interactive console

plus the power of IPython notebook

Python as a calculator:

In [1]:
2 + 5

7

In [2]:
8 * 8.583 * 0.927 * 2

127.30305600000001

In [5]:
21 % 3

0

In [8]:
22 / 3

7.333333333333333

In [7]:
21 // 3

7

Default data types in Python:

In [9]:
type(0.5)

float

In [10]:
type(5)

int

In [11]:
type("Some text")

str

In [12]:
type(False)

bool

## Python state of the art

### Functions

Below you can see an example of function with default argument:

In [27]:
def should_i_work(day_of_week, phd_student=True):
    # here we check if list of strings contains our parameter
    if day_of_week in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]:
        print("Yes!")
    # if not we check if the parameter is exactly Saturday
    elif day_of_week == "Saturday":
        if phd_student:
            print("Yes :/")
        else:
            print("No :)")
    # or Sunday
    elif day_of_week == "Sunday":
        print("No")
    # 
    else:
        print("It's not even a day. You are overworked!")

In [29]:
should_i_work("sdfdsf")

It's not even a day. You are overworked!


We can accept also unknown number of arguments:

In [14]:
def fun(*args):
    for i in args:
        print(i)
        
fun(1,2,3,4)

1
2
3
4


### Loops

In [17]:
for i in [1, 2, 3, 4, 5]:
    print(i**3)

1
8
27
64
125


In [19]:
x = 0
while x < 5:
    x += 1
x

5

## Basic datatypes

### Lists

In [20]:
lst = [1, 2, 3, "a"]

In [21]:
lst.append(99)
lst

[1, 2, 3, 'a', 99]

In [22]:
lst.pop()

99

In [23]:
lst[0]

1

In [24]:
lst[-1]

'a'

In [25]:
lst[::-1]

['a', 3, 2, 1]

In [26]:
len(lst)

4

### Sets

In [30]:
s = set([1, 1, 2, 2, 3, 3])

In [31]:
print('Before:', len(s))
s.add(3)
print('Added 3:', len(s))
s.add(8)
print('Added 8:', len(s))

Before: 3
Added 3: 3
Added 8: 4


### Dictionaries

In [32]:
d1 = dict([("a", 1), ("b", [1, 2, 3]), ("c", "abc")])
d2 = {"a" : 1, "b" : [1, 2, 3], "c" : "abc"}
d1 == d2

True

In [34]:
"a" in d1

True

In [33]:
for k, v in d1.items():
    print(k, v)

a 1
b [1, 2, 3]
c abc


## Objects

In [ ]:
class Duck(object):

    def __init__(self, name):
        self.name = name

    def quack(self):
        return "quack"

## Python tricks

### Iterators

In [35]:
range(9)

range(0, 9)

In [39]:
for i in range(9):
    print(i, end="-")

0-1-2-3-4-5-6-7-8-

In [36]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [40]:
list(range(3, 9))

[3, 4, 5, 6, 7, 8]

### Generators 

In [ ]:
def gen_doubles():
    i = 0
    while True:
        i += 1
        yield 2*i

In [ ]:
for i in gen_doubles():
    print(i, end= " ")
    if i >= 20:
        break

### List comprehension

In [41]:
[x for x in range(7)]

[0, 1, 2, 3, 4, 5, 6]

In [42]:
[x for x in range(7) if x != 3]

[0, 1, 2, 4, 5, 6]

In [43]:
[x if x % 2 else "spam" for x in range(9, 15)]

[9, 'spam', 11, 'spam', 13, 'spam']

Works also with tuples and dictionaries!

Two must have functions while dealing with sequential data.

## String manipulation

In [44]:
"It is a string"

'It is a string'

You can perform some arithmetic operation on strings (if it makes sense...)

In [45]:
"Ruby is cool" + " " + "but Python cooler"

'Ruby is cool but Python cooler'

In [46]:
5 * "la"

'lalalalala'

In [49]:
"Our result number {n} is: {ratio:.3f}".format(n=15, ratio=3/7)

'Our result number 15 is: 0.429'

Strings are objects (as everything is Python) and have some useful methods:

In [50]:
"snake".upper()

'SNAKE'

In [51]:
"snake".replace("sn", "dr")

'drake'

In [52]:
"snake".find("ak")

2

Strings can be indexed just as lists:

In [53]:
"It is a whole sentence!"[6:13]

'a whole'

In [54]:
"It is a whole sentence!"[-3:]


'ce!'

In [55]:
len("It is a whole sentence!")

23

In [56]:
"It\nis\na\nmultiline\nthing\n!!!"

'It\nis\na\nmultiline\nthing\n!!!'

In [57]:
print("It\nis\na\nmultiline\nthing\n!!!")

It
is
a
multiline
thing
!!!


In [58]:
" ".join(["a" , "b", "c"])

'a b c'

## A quick glance at NumPy

NumPy is the fundamental package for scientific computing with Python. It contains a powerful N-dimensional array object, sophisticated (broadcasting) functions, tools for integrating C/C++ and Fortran code, useful linear algebra, Fourier transform, and random number capabilities.

In [59]:
import numpy as np

In [60]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
a.shape

(3, 5)

In [62]:
a.ndim

2

In [64]:
a.dtype

dtype('int64')

In [63]:
(a + 1)*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [65]:
x = np.linspace( 0, 2*np.pi, 100 )
np.sin(x)

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,